services:
  app:
    build: .
    container_name: psicoia_app
    env_file: .env
    command: ["python", "-m", "app.server"]
    ports:
      - "${APP_PORT:-5001}:5001"
  # no DB dependency

  gateway:
    build: .
    container_name: psicoia_gateway
    env_file: .env
    command: ["python", "-m", "gateway.ws_gateway"]
    ports:
      - "8765:8765"
    depends_on:
      app:
        condition: service_started
  # DB services removed per project decision
